// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/2/2026, 7:33:50 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/muteule/Coding/kick-github-unfollows/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/muteule/Coding/kick-github-unfollows/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/muteule/Coding/kick-github-unfollows/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/muteule/Coding/kick-github-unfollows/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/muteule/Coding/kick-github-unfollows/app/plugins/**/*.{js,ts,mjs}","/home/muteule/Coding/kick-github-unfollows/app/composables/**/*.{js,ts,mjs}","/home/muteule/Coding/kick-github-unfollows/app/utils/**/*.{js,ts,mjs}","/home/muteule/Coding/kick-github-unfollows/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/muteule/Coding/kick-github-unfollows/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/muteule/Coding/kick-github-unfollows/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/muteule/Coding/kick-github-unfollows/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;